# -*- coding: utf-8 -*-
"""AI-Based Resume and Portfolio Builder.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dOp0dFMm6387J8BkBQlvXbfVKtKoLopf

**Resume and Portfolio Builder using Machine Learning and Generative AI**
"""

!pip install -q scikit-learn transformers reportlab

import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from transformers import pipeline
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4

data = {
    "skills": [
        "python machine learning data analysis pandas",
        "html css javascript react",
        "aws cloud docker kubernetes",
        "network security ethical hacking cryptography",
        "deep learning neural networks artificial intelligence"
    ],
    "role": [
        "Data Scientist",
        "Web Developer",
        "Cloud Engineer",
        "Cyber Security Analyst",
        "AI Engineer"
    ]
}

df = pd.DataFrame(data)

vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(df["skills"])
y = df["role"]

model = MultinomialNB()
model.fit(X, y)

print("ML Model Trained Successfully!")

name = input("Enter your name: ")
email = input("Enter email: ")
skills_input = input("Enter your skills: ")
projects = input("Describe your project: ")

skills_vector = vectorizer.transform([skills_input])
predicted_role = model.predict(skills_vector)[0]

print("Predicted Job Role:", predicted_role)

generator = pipeline("text-generation", model="gpt2")

objective_prompt = f"Career Objective: A motivated {predicted_role} skilled in {skills_input} seeking"

objective = generator(
    objective_prompt,
    max_new_tokens=30,
    temperature=0.7,
    do_sample=True
)[0]["generated_text"]

print("\nAI Career Objective:\n", objective)

project_prompt = f"Project Description: This project involves {projects}. It focuses on"

project_text = generator(
    project_prompt,
    max_new_tokens=40,
    temperature=0.7,
    do_sample=True
)[0]["generated_text"]

print("\nAI Project Description:\n", project_text)

resume_text = f"""
{name}

Email: {email}

Predicted Role: {predicted_role}

{objective}

Skills:
{skills_input}

{project_text}
"""

print(resume_text)

file_name = "AI_Resume.pdf"
c = canvas.Canvas(file_name, pagesize=A4)

y = 800
for line in resume_text.split("\n"):
    c.drawString(40, y, line)
    y -= 15
    if y < 40:
        c.showPage()
        y = 800

c.save()

from google.colab import files
files.download("AI_Resume.pdf")